### PR TITLE
Qt660

### PR DESCRIPTION
**Pull request by sithlord48**
- Use Qt 6.6.0
 - Replace qAsConst with std::as_const
 - update vcpkg ff7tk to 0.83.3

### CODE REVIEW

**Review by jeromearz — APPROVED** [review]

**Review by myst6re — APPROVED** [review]

**Comment by sithlord48** [comment]
Added change to vcpkg.json  so use ff7tk 0.83.3

**Comment by myst6re** [comment]
Is it ready to merge?

**Comment by sithlord48** [comment]
Yes, it should be pulling the proper ff7tk

**Comment by myst6re** [comment]
Thanks

**Pull request merged**
