### PR TITLE
SpanishTranslation WIP

### PR DESCRIPTION
**Pull request by TurBoss**
I have a question

I should also translate technical words like IF or Add etc..?

### CODE REVIEW

**Comment by TurBoss** [comment]
sry i was thinking that the PR was wrong
reopening

**Comment by myst6re** [comment]
Hello, it seems that you used the dummy file Makou_Reactor_en.ts as a base to translate into spanish. This file is old and totally incorrect, mainly because we don't translate Makou Reactor from french anymore.
I don't know how painful the change will be for you, but here some advices:

- Use Qt Linguist application or lupdate/lrelease to translate the application.
- Create a fresh translation file with lupdate or ask me

Sorry I didn't see your pull request earlier.

**Comment by TurBoss** [comment]
will do thx

**Comment by TurBoss** [comment]
Will create a new PR when i have the translation finished

thanks

**Pull request closed without merging**
